local BS = BearSynergies
local T = BS.Track
local LAM = LibAddonMenu2

function T.BuildMenu()
  local panelData = BS.GetModulePanelData("Track")

  local optionsTable = {
    {
      type = "submenu",
      name = "|cFFFACDSynergies|r",
      controls = {
        {
          type = "checkbox",
          name = "Shackle",
          width = "half",
          getFunc = function() return T.savedVariables.synergies.shackle end,
          setFunc = function(value) T.savedVariables.synergies.shackle = value end,
        },
        {
          type = "texture",
          width = "half",
          image = "esoui/art/icons/ability_dragonknight_006.dds",
          imageWidth = 50,
          imageHeight = 50,
        },
        {
          type = "checkbox",
          name = "Ignite",
          width = "half",
          getFunc = function() return T.savedVariables.synergies.ignite end,
          setFunc = function(value) T.savedVariables.synergies.ignite = value end,
        },
        {
          type = "texture",
          width = "half",
          image = "esoui/art/icons/ability_dragonknight_010.dds",
          imageWidth = 50,
          imageHeight = 50,
        },
        {
          type = "checkbox",
          name = "Grave Robber",
          width = "half",
          getFunc = function() return T.savedVariables.synergies.graveRobber end,
          setFunc = function(value) T.savedVariables.synergies.graveRobber = value end,
        },
        {
          type = "texture",
          width = "half",
          image = "esoui/art/icons/ability_necromancer_004.dds",
          imageWidth = 50,
          imageHeight = 50,
        },
        {
          type = "checkbox",
          name = "Pure Agony",
          width = "half",
          getFunc = function() return T.savedVariables.synergies.pureAgony end,
          setFunc = function(value) T.savedVariables.synergies.pureAgony = value end,
        },
        {
          type = "texture",
          width = "half",
          image = "esoui/art/icons/ability_necromancer_010_b.dds",
          imageWidth = 50,
          imageHeight = 50,
        },
        {
          type = "checkbox",
          name = "Hidden Refresh",
          width = "half",
          getFunc = function() return T.savedVariables.synergies.hiddenRefresh end,
          setFunc = function(value) T.savedVariables.synergies.hiddenRefresh = value end,
        },
        {
          type = "texture",
          width = "half",
          image = "esoui/art/icons/ability_nightblade_015.dds",
          imageWidth = 50,
          imageHeight = 50,
        },
        {
          type = "checkbox",
          name = "Soul Leech",
          width = "half",
          getFunc = function() return T.savedVariables.synergies.soulLeech end,
          setFunc = function(value) T.savedVariables.synergies.soulLeech = value end,
        },
        {
          type = "texture",
          width = "half",
          image = "esoui/art/icons/ability_nightblade_018.dds",
          imageWidth = 50,
          imageHeight = 50,
        },
        {
          type = "checkbox",
          name = "Charged Lightning",
          width = "half",
          getFunc = function() return T.savedVariables.synergies.chargedLightning end,
          setFunc = function(value) T.savedVariables.synergies.chargedLightning = value end,
        },
        {
          type = "texture",
          width = "half",
          image = "esoui/art/icons/ability_sorcerer_storm_atronach.dds",
          imageWidth = 50,
          imageHeight = 50,
        },
        {
          type = "checkbox",
          name = "Conduit",
          width = "half",
          getFunc = function() return T.savedVariables.synergies.conduit end,
          setFunc = function(value) T.savedVariables.synergies.conduit = value end,
        },
        {
          type = "texture",
          width = "half",
         image = "esoui/art/icons/ability_sorcerer_lightning_splash.dds",
          imageWidth = 50,
          imageHeight = 50,
        },
        {
          type = "checkbox",
          name = "Nova",
          width = "half",
          getFunc = function() return T.savedVariables.synergies.nova end,
          setFunc = function(value) T.savedVariables.synergies.nova = value end,
        },
        {
          type = "texture",
          width = "half",
          image = "esoui/art/icons/ability_templar_nova.dds",
          imageWidth = 50,
          imageHeight = 50,
        },
        {
          type = "checkbox",
          name = "Purify",
          width = "half",
          getFunc = function() return T.savedVariables.synergies.purify end,
          setFunc = function(value) T.savedVariables.synergies.purify = value end,
        },
        {
          type = "texture",
          width = "half",
          image = "esoui/art/icons/ability_templar_cleansing_ritual.dds",
          imageWidth = 50,
          imageHeight = 50,
        },
        {
          type = "checkbox",
          name = "Harvest",
          width = "half",
          getFunc = function() return T.savedVariables.synergies.harvest end,
          setFunc = function(value) T.savedVariables.synergies.harvest = value end,
        },
        {
          type = "texture",
          width = "half",
          image = "esoui/art/icons/ability_warden_007.dds",
          imageWidth = 50,
          imageHeight = 50,
        },
        {
          type = "checkbox",
          name = "Icy Escape",
          width = "half",
          getFunc = function() return T.savedVariables.synergies.icyEscape end,
          setFunc = function(value) T.savedVariables.synergies.icyEscape = value end,
        },
        {
          type = "texture",
          width = "half",
          image = "esoui/art/icons/ability_warden_005_b.dds",
          imageWidth = 50,
          imageHeight = 50,
        },
        {
          type = "checkbox",
          name = "Feeding Frenzy",
          width = "half",
          getFunc = function() return T.savedVariables.synergies.feedingFrenzy end,
          setFunc = function(value) T.savedVariables.synergies.feedingFrenzy = value end,
        },
        {
          type = "texture",
          width = "half",
          image = "esoui/art/icons/ability_werewolf_005_b.dds",
          imageWidth = 50,
          imageHeight = 50,
        },
        {
          type = "checkbox",
          name = "Blood Altar",
          width = "half",
          getFunc = function() return T.savedVariables.synergies.bloodAltar end,
          setFunc = function(value) T.savedVariables.synergies.bloodAltar = value end,
        },
        {
          type = "texture",
          width = "half",
          image = "esoui/art/icons/ability_undaunted_001.dds",
          imageWidth = 50,
          imageHeight = 50,
        },
        {
          type = "checkbox",
          name = "Spiders",
          width = "half",
          getFunc = function() return T.savedVariables.synergies.spiders end,
          setFunc = function(value) T.savedVariables.synergies.spiders = value end,
        },
        {
          type = "texture",
          width = "half",
          image = "esoui/art/icons/ability_undaunted_003.dds",
          imageWidth = 50,
          imageHeight = 50,
        },
        {
          type = "checkbox",
          name = "Radiate",
          width = "half",
          getFunc = function() return T.savedVariables.synergies.radiate end,
          setFunc = function(value) T.savedVariables.synergies.radiate = value end,
        },
        {
          type = "texture",
          width = "half",
          image = "esoui/art/icons/ability_undaunted_002.dds",
          imageWidth = 50,
          imageHeight = 50,
        },
        {
          type = "checkbox",
          name = "Bone Shield",
          width = "half",
          getFunc = function() return T.savedVariables.synergies.boneShield end,
          setFunc = function(value) T.savedVariables.synergies.boneShield = value end,
        },
        {
          type = "texture",
          width = "half",
          image = "esoui/art/icons/ability_undaunted_005.dds",
          imageWidth = 50,
          imageHeight = 50,
        },
        {
          type = "checkbox",
          name = "Spear Shards/Combustion",
          width = "half",
          getFunc = function() return T.savedVariables.synergies.orb end,
          setFunc = function(value) T.savedVariables.synergies.orb = value end,
        },
        {
          type = "texture",
          width = "half",
          image = "esoui/art/icons/ability_undaunted_004.dds",
          imageWidth = 50,
          imageHeight = 50,
        },
      },
    },
  }

  LAM:RegisterAddonPanel(BS.name .. "Track", panelData)
  LAM:RegisterOptionControls(BS.name .. "Track", optionsTable)
end